//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppointmentBookSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_User
    {
        public int User_Id { get; set; }
        public string User_Username { get; set; }
        public string User_Password { get; set; }
        public Nullable<int> User_Role_Id { get; set; }
    }
}
