//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppointmentBookSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Appointment
    {
        internal object tbl_Appointment_Status;
        internal object tbl_Doctor;
        internal object tbl_Patient;

        public int Appoitment_Id { get; set; }
        public System.DateTime Appoitment_Date { get; set; }
        public Nullable<System.DateTime> Appoitment_Time { get; set; }
        public string Appoitment_Details { get; set; }
        public Nullable<int> Appoitment_Status { get; set; }
        public Nullable<int> Appoitment_Patient_Id { get; set; }
        public Nullable<int> Appoitment_Doctor_Id { get; set; }
        public object Appointment_Patient_Id { get; internal set; }
        public object Appointment_Doctor_Id { get; internal set; }
    }
}
