//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppointmentBookSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Patient
    {
        public int Patient_Id { get; set; }
        public string Patient_Name { get; set; }
        public string Patient_Username { get; set; }
        public string Patient_Password { get; set; }
        public string Patient_Gender { get; set; }
        public System.DateTime Patient_DOB { get; set; }
        public string Patient_Phone { get; set; }
        public string Patient_Address { get; set; }
        public string Patient_City { get; set; }
        public string Patient_Height { get; set; }
        public string Patient_Weight { get; set; }
    }
}
